# Generated by Django 5.2.7 on 2026-01-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campus', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='CCSLNaoDGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ccsl_nao_dgp',
            },
        ),
        migrations.CreateModel(
            name='PesquisadoresCCSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ccsl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pesquisadores_site',
            },
        ),
        migrations.CreateModel(
            name='PesquisadoresDGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dgp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pesquisadores_dgp',
            },
        ),
        migrations.CreateModel(
            name='RedmineCCSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'redmine_ccsl',
            },
        ),
        migrations.CreateModel(
            name='RedmineDGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'redmine_dgp',
            },
        ),
        migrations.CreateModel(
            name='RedmineNaoDGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'redmine_nao_dgp',
            },
        ),
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_formacao', models.IntegerField(blank=True, null=True)),
                ('link_cnpq', models.URLField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='grupos_pesquisa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('idlattes', models.CharField(max_length=100, unique=True)),
                ('funcao', models.CharField(choices=[('Professor', 'Professor'), ('Técnico', 'Técnico'), ('Aluno', 'Aluno'), ('Alumni', 'Alumni')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultima_extracao_em', models.DateTimeField(blank=True, null=True)),
                ('status_extracao', models.CharField(default='Pendente', max_length=50)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalab.campus')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalab.grupopesquisa')),
                ('usuario_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('discentes', models.TextField(blank=True, help_text='Nomes dos alunos orientados.', null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='datalab.pesquisador')),
            ],
            options={
                'verbose_name': 'Orientação',
                'verbose_name_plural': 'Orientações',
            },
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='datalab.pesquisador')),
            ],
            options={
                'verbose_name': 'Projeto de Pesquisa',
                'verbose_name_plural': 'Projetos de Pesquisa',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('categoria', models.TextField(blank=True, null=True)),
                ('subcategoria', models.TextField(blank=True, null=True)),
                ('ccsl', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='datalab.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoGeral',
            fields=[
                ('pesquisador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datalab.pesquisador')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('producoes_tecnicas', models.IntegerField(default=0)),
                ('producoes_bibliograficas', models.IntegerField(default=0)),
                ('orientacoes', models.IntegerField(default=0)),
                ('projetos_pesquisa', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
            ],
            options={
                'verbose_name': 'Produção Geral',
                'verbose_name_plural': 'Produções Gerais',
            },
        ),
    ]
