# Generated by Django 5.2.5 on 2025-09-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('idlattes', models.CharField(max_length=100, unique=True)),
                ('funcao', models.CharField(choices=[('Professor', 'Professor'), ('Técnico', 'Técnico'), ('Aluno', 'Aluno'), ('Alumni', 'Alumni')], default='Aluno', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultima_extracao_em', models.DateTimeField(blank=True, help_text='Data e hora da última extração de dados do Lattes.', null=True)),
                ('status_extracao', models.CharField(default='Pendente', max_length=50)),
                ('campus', models.ForeignKey(blank=True, help_text='Campus principal do pesquisador.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalab.campus')),
                ('usuario_vinculado', models.OneToOneField(blank=True, help_text='Conta de login associada a este perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('discentes', models.TextField(blank=True, help_text='Nomes dos alunos orientados.', null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='datalab.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='datalab.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('categoria', models.TextField(blank=True, null=True)),
                ('subcategoria', models.TextField(blank=True, null=True)),
                ('ccsl', models.BooleanField(default=False, help_text='Indica se a publicação está relacionada ao CCSL.')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='datalab.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoGeral',
            fields=[
                ('pesquisador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datalab.pesquisador')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('producoes_tecnicas', models.IntegerField(default=0)),
                ('producoes_bibliograficas', models.IntegerField(default=0)),
                ('orientacoes', models.IntegerField(default=0)),
                ('projetos_pesquisa', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.campus')),
            ],
        ),
    ]
