# Generated by Django 5.2.5 on 2025-09-10 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='orientacao',
            options={'verbose_name': 'Orientação', 'verbose_name_plural': 'Orientações'},
        ),
        migrations.AlterModelOptions(
            name='pesquisador',
            options={'verbose_name': 'Pesquisador', 'verbose_name_plural': 'Pesquisadores'},
        ),
        migrations.AlterModelOptions(
            name='producaogeral',
            options={'verbose_name': 'Produção Geral', 'verbose_name_plural': 'Produções Gerais'},
        ),
        migrations.AlterModelOptions(
            name='projetopesquisa',
            options={'verbose_name': 'Projeto de Pesquisa', 'verbose_name_plural': 'Projetos de Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalab.grupopesquisa'),
        ),
    ]
