# Generated by Django 5.2.7 on 2026-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccslnaodgp',
            name='nome',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pesquisadoresccsl',
            name='nome_ccsl',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pesquisadoresdgp',
            name='nome_dgp',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='redmineccsl',
            name='nome',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='redminedgp',
            name='nome',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='redminenaodgp',
            name='nome',
            field=models.CharField(max_length=256),
        ),
    ]
