# Generated by Django 5.2.7 on 2026-01-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0002_alter_ccslnaodgp_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisadoresccsl',
            name='tipo',
            field=models.CharField(default='desconhecido', max_length=100),
        ),
    ]
