# Generated by Django 5.2.5 on 2025-09-12 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0002_alter_campus_options_alter_orientacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopesquisa',
            name='usuarios',
            field=models.ManyToManyField(related_name='grupos_pesquisa', to=settings.AUTH_USER_MODEL),
        ),
    ]
