# Generated by Django 5.2.5 on 2025-09-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0003_grupopesquisa_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupopesquisa',
            name='usuarios',
        ),
    ]
