# Generated by Django 5.2.7 on 2026-01-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0003_pesquisadoresccsl_tipo'),
        ('extracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RODANDO', 'Rodando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.pesquisador')),
            ],
        ),
        migrations.DeleteModel(
            name='ExtracaoStatus',
        ),
    ]
