from .home_publica import home_publica
from .lista_pesquisadores import lista_publica_pesquisadores
from .lista_grupos import lista_publica_grupos
from .dashboard_geral import dashboard_geral
from .dashboard_grupo import dashboard_grupo
from .selecionar_grupo import selecionar_grupo
from .detalhes_grupo import detalhes_grupo_publico
from .detalhes_pesquisador import detalhes_pesquisador_publico
from .auth import logout_view
from .painel_comparador import painel_comparador
from .home import home_redirect
from .executar_comparacao import executar_comparacao
